# /********************************************************************************
# * Copyright (c) 2023 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Apache License 2.0 which is available at
# * https://www.apache.org/licenses/LICENSE-2.0
# *
# * SPDX-License-Identifier: Apache-2.0
# ********************************************************************************/

name: Leda-Utils Release

on:
  release:
    types: [published]

jobs:
  call-build:
    name: Build
    uses: ./.github/workflows/build.yaml
    secrets: inherit

  upload-assets:
    name: Upload assets
    runs-on: ubuntu-latest
    needs: [ call-build ]
    permissions:
      contents: write
    steps:
      - name: Download build artifacts
        id: download
        uses: actions/download-artifact@v4
        with:
          path: build/
      - name: Upload assets
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          files: |
            ${{steps.download.outputs.download-path}}/kantui-*-packages/eclipse-leda-kantui_*_amd64.deb
            ${{steps.download.outputs.download-path}}/kantui-*-packages/eclipse-leda-kantui_*_arm64.deb
            ${{steps.download.outputs.download-path}}/kantui-*-packages/eclipse-leda-kantui*.x86_64.rpm
            ${{steps.download.outputs.download-path}}/kantui-*-packages/eclipse-leda-kantui*.arm64.rpm
            ${{steps.download.outputs.download-path}}/kanto-auto-deployer-*-packages/eclipse-leda-kanto-auto-deployer_*_amd64.deb
            ${{steps.download.outputs.download-path}}/kanto-auto-deployer-*-packages/eclipse-leda-kanto-auto-deployer_*_arm64.deb
            ${{steps.download.outputs.download-path}}/kanto-auto-deployer-*-packages/eclipse-leda-kanto-auto-deployer*.x86_64.rpm
            ${{steps.download.outputs.download-path}}/kanto-auto-deployer-*-packages/eclipse-leda-kanto-auto-deployer*.arm64.rpm
            ${{steps.download.outputs.download-path}}/leda-utils-packages/eclipse-leda-utils*.deb
            ${{steps.download.outputs.download-path}}/leda-utils-packages/eclipse-leda-utils*.noarch.rpm
            
